version: "3.9"

services:
  web:
    build: ./instacopy
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./instacopy:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.6
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db
    ports:
      - 5432:5432