version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./instacopy:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: instacopy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
